[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
corelib = { version = "0.1.0", path = "../corelib" }
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["rt", "macros"] }
