[package]
name = "corelib"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
rsa = "0.9.8"
serde = { version = "1.0.219", features=["derive"]}
sha2 = "0.10.8"
rand = "0.8.0"